#!/bin/sh
# Start/stop the pmatic-manager daemon.
#
### BEGIN INIT INFO
# Provides:          pmatic-manager
# Required-Start:    $remote_fs $syslog $time
# Required-Stop:     $remote_fs $syslog $time
# Should-Start:      $network $named slapd autofs ypbind nscd nslcd winbind sssd
# Should-Stop:       $network $named slapd autofs ypbind nscd nslcd winbind sssd
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Regular background program processing daemon
# Description:       pmatic-manager
#                    programs at periodic scheduled times....
### END INIT INFO

PATH=/bin:/usr/bin:/sbin:/usr/sbin
DESC="pmatic-manager daemon"
NAME=pmatic-manager
DAEMON=/usr/local/bin/pmatic-manager
PIDFILE=/var/run/pmatic-manager.pid
SCRIPTNAME=/etc/init.d/"$NAME"

test -f $DAEMON || exit 0

. /lib/lsb/init-functions

[ -r /etc/default/pmatic-manager ] && . /etc/default/pmatic-manager

case "$1" in
start)	log_daemon_msg "Starting" "pmatic-manager"
        start_daemon -p $PIDFILE $DAEMON $EXTRA_OPTS
        log_end_msg $?
	;;
stop)	log_daemon_msg "Stopping" "pmatic-manager"
        kill `cat $PIDFILE`
        #killproc -p $PIDFILE
        RETVAL=$?
        [ $RETVAL -eq 0 ] && [ -e "$PIDFILE" ] && rm -f $PIDFILE
        log_end_msg $RETVAL
        ;;
restart) log_daemon_msg "Restarting " "pmatic-manager" 
        $0 stop
        $0 start
        ;;
status)
        status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
        ;;
*)	log_action_msg "Usage: /etc/init.d/pmatic-manager {start|stop|status|restart}"
        exit 2
        ;;
esac
exit 0
